# Generated by Django 5.2.4 on 2026-01-18 15:52

import Bookstore.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('portrait', models.ImageField(null=True, upload_to=Bookstore.utils.get_upload_path)),
                ('birth_date', models.DateField(null=True)),
                ('death_date', models.DateField(null=True)),
                ('bio', models.TextField()),
            ],
        ),
    ]
